### ISSUE TITLE
ArrayIndexOutOfBoundsException in BufferedRandomAccessFile

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/utilities#103]
```
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at de.cebitec.mgx.braf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java:67)
        at de.cebitec.mgx.seqstorage.CSQFReader.getEntry(CSQFReader.java:192)
        at de.cebitec.mgx.seqstorage.CSQFReader.hasMoreElements(CSQFReader.java:133)

```

**Comment by sjaenick** [comment]
unable to reproduce, closing
