### ISSUE TITLE
ArrayIndexOutOfBoundsException in MGX-seqstorage

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/utilities#104]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 36734020
        at gnu.trove.impl.hash.TLongLongHash.indexRehashed(TLongLongHash.java:248)
        at gnu.trove.impl.hash.TLongLongHash.index(TLongLongHash.java:234)
        at gnu.trove.impl.hash.TLongLongHash.contains(TLongLongHash.java:178)
        at gnu.trove.map.hash.TLongLongHashMap.containsKey(TLongLongHashMap.java:387)
        at de.cebitec.mgx.seqstorage.NMSReader.getOffset(NMSReader.java:28)
        at de.cebitec.mgx.seqstorage.CSFReader.fetch(CSFReader.java:162)
        at de.cebitec.mgx.download.SeqByAttributeDownloadProvider.run(SeqByAttributeDownloadProvider.java:119)
```

**Comment by sjaenick** [comment]
downstream error after running out of heap space, closing
