### ISSUE TITLE
Unable to obtain SeqReader for large datasets, file size too large

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/utilities#105]
```
java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:863)
        at de.cebitec.mgx.seqstorage.NMSIndex.<init>(NMSIndex.java:34)
        at de.cebitec.mgx.seqstorage.NMSIndex.<init>(NMSIndex.java:28)
        at de.cebitec.mgx.seqstorage.CSQFReader.<init>(CSQFReader.java:41)
        at de.cebitec.mgx.seqstorage.ReaderFactory.getReader(ReaderFactory.java:72)
        at de.cebitec.mgx.sequence.SeqReaderFactory.getReader(SeqReaderFactory.java:29)
```

**Comment by sjaenick** [comment]
FileChannel#map() does not support more than 2GB to be mapped, need to convert into separate slices
